# Generated by Django 4.2 on 2023-12-30 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("financial_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={"verbose_name": "Orçamento", "verbose_name_plural": "Orçamentos"},
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={"verbose_name": "Transação", "verbose_name_plural": "Transações"},
        ),
        migrations.RenameField(
            model_name="budget",
            old_name="update_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="category",
            old_name="update_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
