# Generated by Django 5.0 on 2023-12-15 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criação"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualização"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome da família"),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Integrantes da família",
                    ),
                ),
            ],
            options={
                "verbose_name": "Família",
                "verbose_name_plural": "Famílias",
            },
        ),
    ]
